### ISSUE TITLE
Datenmodell: Musiker als Autoren

### ISSUE THREAD

**Issue by ttepasse** [Actionb/MIZDB#17]
Ich habe gerade eine Zeitschrift-Sonderausgabe, in der nur Musiker als Autoren auftreten (Musikexpress/Sounds Dezember 1992). Funktional geht das mit einem Umweg statt des Autocomplete-Felds: Man kann einen neuen Autor erstellen und dann die Person hinter dem Musiker zuordnen; die Verknüpfung zwischen den Datensätzen funktioniert also.

Aber ästhetisch ist es schwierig: Als Autor taucht dann natürlich der legale Name statt des Künstlernamens auf ("Tracy Lauren Marrow" statt "Ice-T"). Und natürlich kann man keine Band als Autor bestimmen, sondern nur die einzelnen Personen, die diese Band ausmachen.

Vielleicht ist die einfachste Lösung nur eine Frage der Darstellung: Wenn die Person hinter dem Autor auch Musiker ist, dann verwende den Künstlernamen, ähnlich wie das optionale Kürzel in den synthesierten Autorennamen integriert wird.

**Comment by Actionb** [comment]
Ich würde dann bei den Artikeln einfach eher keine Autoren angeben, sondern nur die Musiker/Bands. Zusätzlich könnte man in der Zusammenfassung oder Beschreibung angeben, dass der Artikel von den Künstlern geschrieben wurde. Auch in der Beschreibung der Ausgabe könnte man das so erwähnen.

Ich stimme aber zu, dass das Datenmodell manchmal zu umständlich ist. Sobald ich die neue "UI" endlich hinzugefügt habe, gucke ich nochmal, ob man einige Modelle nicht auch glatter machen könnte (z.B. Autoren, Personen).
